export const GAME = {
  width: 800,
  height: 600,
  targetFps: 120,
  maxFrameSeconds: 1 / 30,
  physicsStepSeconds: 1 / 120,
  lives: 3,
  initialBallSpeed: 320,
  minBallSpeed: 260,
  maxBallSpeed: 680,
  speedupPerHit: 3,
  stickSpeed: 540,
  minStickSpeed: 320,
  maxStickSpeed: 700,
  stickStartX: 400,
  stickStartY: 565,
  upperStickY: 465,
  sidePadding: 5,
  topWallY: 0,
  ballRadius: 13,
  launchAngle: 35,
  maxBounceAngle: 56,
  maxSpin: 18,
  paddleSpinTransfer: 12,
  edgeSpinTransfer: 5,
  spinFlightCurve: 0.025,
  spinBounceDeflection: 0.045,
  spinBounceDamping: 0.82,
  spinDamping: 0.35,
  itemChance: 0.08,
  itemChanceStep: 0.025,
  itemFallSpeed: 210,
  fasterStickBoost: 60,
  slowerStickPenalty: 50,
  fasterBallBoost: 45,
  slowerBallPenalty: 45,
} as const;

export const ASSETS = {
  font: "/font/fixedsys.ttf",
  images: {
    background: "/images/background.png",
    ball: "/images/ball.png",
    stick: "/images/stick.png",
    stickBigger: "/images/stickBigger.png",
    stickSmaller: "/images/stickSmaller.png",
    blocks: ["/images/block_1.png", "/images/block_2.png", "/images/block_3.png", "/images/block_4.png"] as const,
    heart: "/images/heart.png",
    bar: "/images/balken.png",
    menu: "/images/menu.png",
    gameOver: "/images/gameover_new.png",
    gameWon: "/images/gamewontest.png",
    help: "/images/helpbackground.png",
    about: "/images/abouttestimage.png",
    items: {
      fasterStick: "/images/faster.png",
      slowerStick: "/images/slower.png",
      biggerStick: "/images/bigger.png",
      smallerStick: "/images/smaller.png",
      fasterBall: "/images/fasterball.png",
      slowerBall: "/images/slowerball.png",
    },
  },
  sounds: {
    background: "/sounds/backgroundMusic.wav",
    block: "/sounds/hitBlock.wav",
    stick: "/sounds/hitStick.wav",
    border: "/sounds/border.wav",
    item: "/sounds/itemHitStick.wav",
    gameOver: "/sounds/game-over-yeah.wav",
    win: "/sounds/winSound.wav",
    click: "/sounds/click.wav",
    lostLife: "/sounds/evil-laugh.wav",
  },
} as const;

export const MAPS = [
  "level1.map",
  "levelBlock1.map",
  "levelBlockTest5.map",
  "levelEmpty.map",
  "levelTest2.map",
  "levelTestBlock.map",
] as const;

export type GameMode = "single" | "multi";
export type Screen = "menu" | "playing" | "paused" | "gameover" | "won" | "highscores" | "help" | "about";
